/**
https://leetcode.com/problems/find-the-difference/
389. Find the Difference  QuestionEditorial Solution  My Submissions
Total Accepted: 2806 Total Submissions: 4659 Difficulty: Easy
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
Show Company Tags
Show Tags
Show Similar Problems

 */
package algorithms.num389_FindTheDifference;

public class Solution {
    public char findTheDifference(String s, String t) {
    	StringBuffer sb = new StringBuffer(s);
        for (int tI = 0; tI < t.length(); tI++) {
        	String tC = t.substring(tI, tI + 1);
        	int i = sb.indexOf(tC);
        	if (i > -1) sb.delete(i, i + 1);
        	else return t.charAt(tI);
        }
        return 0;
    }
}
//SolvedOn20160828SatAt14:17 CodingDuration:27m52s95 Accepted @github.com/BryanBo-Cao,hackerrank.com/bryanbocao,leetcode.com/bryanbocao-0/,linkedin.com/in/bryanbocao 
